export const AFFIRMATIONS = [
  { "title": "Nailed It", "subTitle": "...like a sleepy carpenter" },
  { "title": "Legendary", "subTitle": "but only in your own head" },
  { "title": "Hot Stuff", "subTitle": "careful, that ego might burn" },
  { "title": "Overachiever", "subTitle": "compensating for attention?" },
  { "title": "Big Winner", "subTitle": "tiny victories count too" },
  { "title": "Genius", "subTitle": "at pressing buttons real good" },
  { "title": "Champion", "subTitle": "of wasting time productively" },
  { "title": "MVP", "subTitle": "minimum viable player" },
  { "title": "Too Good", "subTitle": "...to have real friends" },
  { "title": "Clutch", "subTitle": "like your mom’s purse" },
  { "title": "Unstoppable", "subTitle": "except by doors marked 'Push'" },
  { "title": "Big Brain", "subTitle": "small attention span" },
  { "title": "Killer Move", "subTitle": "still can’t dance though" },
  { "title": "Dominating", "subTitle": "but not in a cool way" },
  { "title": "Boss Mode", "subTitle": "minus the paycheck" },
  { "title": "Godlike", "subTitle": "but still can’t parallel park" },
  { "title": "Baller", "subTitle": "on a budget" },
  { "title": "Epic", "subTitle": "like your internet search history" },
  { "title": "Flawless", "subTitle": "except for that one rash" },
  { "title": "Sharp Shooter", "subTitle": "but dull personality" },
  { "title": "Rockstar", "subTitle": "air guitar specialist" },
  { "title": "Slick", "subTitle": "like a greasy taco wrapper" },
  { "title": "Winner", "subTitle": "but participation trophy style" },
  { "title": "Legend", "subTitle": "mostly urban myth" },
  { "title": "Pro Gamer", "subTitle": "unemployed edition" },
  { "title": "Savage", "subTitle": "but cries at Pixar movies" },
  { "title": "Untouchable", "subTitle": "except by student loans" },
  { "title": "Kingpin", "subTitle": "of questionable choices" },
  { "title": "Immortal", "subTitle": "until snack time" },
  { "title": "Hotshot", "subTitle": "lukewarm at best" },
  { "title": "Clown", "subTitle": "but the funny kind" },
  { "title": "Monster", "subTitle": "snacc edition" },
  { "title": "Hero", "subTitle": "in your group chat" },
  { "title": "Wizard", "subTitle": "of 'oops, wrong button'" },
  { "title": "Winner Winner", "subTitle": "sad microwave dinner" },
  { "title": "Certified", "subTitle": "only slightly insane" },
  { "title": "Boss", "subTitle": "but nobody respects you" },
  { "title": "Lethal", "subTitle": "like expired milk" },
  { "title": "Icon", "subTitle": "of poor fashion" },
  { "title": "Beast Mode", "subTitle": "not beauty, though" },
  { "title": "Fire", "subTitle": "but like dumpster fire" },
  { "title": "Alpha", "subTitle": "but only in video games" },
  { "title": "Rocket", "subTitle": "powered by bad decisions" },
  { "title": "Fearless", "subTitle": "unless it’s spiders" },
  { "title": "Turbo", "subTitle": "low-octane fuel only" },
  { "title": "Smooth", "subTitle": "like chunky peanut butter" },
  { "title": "Legendary", "subTitle": "average friend edition" },
  { "title": "Overlord", "subTitle": "of laundry piles" },
  { "title": "Dangerous", "subTitle": "mostly to yourself" },
  { "title": "Savory", "subTitle": "like a stale chip" },
  { "title": "Unreal", "subTitle": "like your dating prospects" },
  { "title": "Magnificent", "subTitle": "spelling not included" },
  { "title": "King", "subTitle": "but of awkward silences" },
  { "title": "Deadly", "subTitle": "with carbs" },
  { "title": "Glorious", "subTitle": "like glitter on everything" },
  { "title": "Tryhard", "subTitle": "and still average" },
  { "title": "Mastermind", "subTitle": "of obvious solutions" },
  { "title": "Savage", "subTitle": "but still grounded by mom" },
  { "title": "Untamed", "subTitle": "like your browser tabs" },
  { "title": "Iron Will", "subTitle": "aluminum execution" },
  { "title": "Hot Mess", "subTitle": "emphasis on mess" },
  { "title": "Captain", "subTitle": "of bad timing" },
  { "title": "Noble", "subTitle": "except your browsing history" },
  { "title": "Bulletproof", "subTitle": "emotionally fragile though" },
  { "title": "Savory Snack", "subTitle": "mostly crumbs" },
  { "title": "Fearsome", "subTitle": "like a hangnail" },
  { "title": "Mega Brain", "subTitle": "tiny common sense" },
  { "title": "Quickdraw", "subTitle": "slow thinker" },
  { "title": "Adorable", "subTitle": "like a gremlin" },
  { "title": "Heroic", "subTitle": "in a very local sense" },
  { "title": "Champion", "subTitle": "average effort edition" },
  { "title": "Absolute Unit", "subTitle": "of procrastination" },
  { "title": "Beefcake", "subTitle": "mostly marshmallow though" },
  { "title": "Epic Fail", "subTitle": "but in style" },
  { "title": "Gladiator", "subTitle": "of online arguments" },
  { "title": "Sneaky", "subTitle": "like browser incognito" },
  { "title": "Titan", "subTitle": "of snack food" },
  { "title": "Majestic", "subTitle": "awkward in motion" },
  { "title": "Wizard", "subTitle": "magic: mostly fumbles" },
  { "title": "Clutch", "subTitle": "like a rusty gear" },
  { "title": "Dominator", "subTitle": "of pillow forts" },
  { "title": "Expert", "subTitle": "at excuses" },
  { "title": "Untouchable", "subTitle": "still ghosted" },
  { "title": "Boss", "subTitle": "tiny kingdom edition" },
  { "title": "Epic Gamer", "subTitle": "missing sleep DLC" },
  { "title": "Warlord", "subTitle": "of dirty socks" },
  { "title": "Ninja", "subTitle": "of snack theft" },
  { "title": "Champion Mode", "subTitle": "still unranked IRL" },
  { "title": "Sniper", "subTitle": "of the last cookie" },
  { "title": "Dramatic", "subTitle": "like your group texts" },
  { "title": "Alpha Wolf", "subTitle": "lone, but awkward" },
  { "title": "Untamed", "subTitle": "houseplants disagree" },
  { "title": "Overpowered", "subTitle": "underqualified elsewhere" },
  { "title": "Danger", "subTitle": "mostly to furniture" },
  { "title": "Flex", "subTitle": "tiny muscles, big ego" },
  { "title": "Elite", "subTitle": "at wasting time" },
  { "title": "Titan", "subTitle": "tiny patience edition" },
  { "title": "Absolute Legend", "subTitle": "of mediocre skills" },
  { "title": "Omega", "subTitle": "last in line" },
  { "title": "Victory", "subTitle": "barely counts" },
  { "title": "Ultra Instinct", "subTitle": "zero coordination" },
  { "title": "Savage Beast", "subTitle": "nap time pending" },
  { "title": "Champion Vibes", "subTitle": "loser aura" }
]
