export interface Affirmation {
  title: string;
  subTitle: string;
  accuracy: number;
  speed: number;
  difficulty: number;
}


export const AFFIRMATIONS: Affirmation[] = [
  { title: "Too Good", subTitle: "...to have real friends", accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: "Boss", subTitle: "but nobody respects you", accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: "Fire", subTitle: "but like dumpster fire", accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: "Savory", subTitle: "like a stale chip", accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: "Hot Mess", subTitle: "emphasis on mess", accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: "Champion Vibes", subTitle: "loser aura", accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: "Overachiever", subTitle: "compensating for attention?", accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: "Pro Gamer", subTitle: "unemployed edition", accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: "Lethal", subTitle: "like expired milk", accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: "Icon", subTitle: "of poor fashion", accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: "Unreal", subTitle: "like your dating prospects", accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: "Tryhard", subTitle: "and still average", accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: "Untouchable", subTitle: "still ghosted", accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: "Omega", subTitle: "last picked", accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: "Legendary", subTitle: "but only in your own head", accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: "Dominating", subTitle: "but not in a cool way", accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: "Sharp Shooter", subTitle: "but dull personality", accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: "Dangerous", subTitle: "mostly to yourself", accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: "King", subTitle: "of awkward silences", accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: "Iron Will", subTitle: "aluminum execution", accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: "Quickdraw", subTitle: "slow thinker", accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: "Expert", subTitle: "at excuses", accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: "Flex", subTitle: "tiny muscles, big ego", accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: "Ultra Instinct", subTitle: "zero coordination", accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: "Flawless", subTitle: "except for that one rash", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Slick", subTitle: "like a greasy taco wrapper", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Winner Winner", subTitle: "sad microwave dinner", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Alpha", subTitle: "but only in video games", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Smooth", subTitle: "like chunky peanut butter", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Hero", subTitle: "in your mind", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Captain", subTitle: "of bad moves", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Mega Brain", subTitle: "tiny common sense", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Epic", subTitle: "failure", accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: "Clutch", subTitle: "like a worn out one", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Boss", subTitle: "tiny kingdom edition", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Overpowered", subTitle: "underqualified elsewhere", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Elite", subTitle: "at wasting time", accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: "Genius", subTitle: "at pointless endeavors", accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: "Legend", subTitle: "...mostly an urban myth", accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: "Wizard", subTitle: "of 'oops, wrong move'", accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: "Legendary", subTitle: "average friend edition", accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: "Savage", subTitle: "but still gets grounded by mom", accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: "Bulletproof", subTitle: "emotionally fragile though", accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: "Champion", subTitle: "average effort edition", accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: "Alpha Wolf", subTitle: "lone. awkward.", accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: "Danger", subTitle: "mostly to furniture", accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: "MVP", subTitle: "minimum viable player", accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: "Winner", subTitle: "but participation trophy style", accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: "Certified", subTitle: "only slightly insane", accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: "Beast Mode", subTitle: "not beauty, though", accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: "Wizard", subTitle: "magic: mostly fumbles", accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: "Champion", subTitle: "still unranked IRL", accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: "Untamed", subTitle: "houseplant collection disagrees", accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: "Absolute Legend", subTitle: "of mediocre skills", accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: "Savage Beast", subTitle: "nap time pending", accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: "Hot Stuff", subTitle: "careful, that ego might burn", accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: "Big Brain", subTitle: "small attention span", accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: "Boss Mode", subTitle: "minus the paycheck", accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: "Mastermind", subTitle: "of obvious solutions", accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: "Dominator", subTitle: "of mistakes", accuracy: -0.92, speed: -0.74, difficulty: -0.72 },
  { title: "Epic Gamer", subTitle: "missing sleep DLC", accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: "Big Winner", subTitle: "tiny victories count too", accuracy: -0.1, speed: -0.08, difficulty: 0.1 },
  { title: "Immortal", subTitle: "until snack time's missed", accuracy: -0.1, speed: -0.08, difficulty: 0.1 },
  { title: "Majestic", subTitle: "awkward in motion", accuracy: -0.1, speed: -0.08, difficulty: 0.1 },
  { title: "Savage", subTitle: "but cries at Pixar movies", accuracy: 0, speed: 0, difficulty: 0.2 },
  { title: "Magnificent", subTitle: "spelling not included", accuracy: 0, speed: 0, difficulty: 0.2 },
  { title: "Famous", subTitle: "in a very local sense", accuracy: 0, speed: 0, difficulty: 0.2 },
  { title: "Unstoppable", subTitle: "except by doors marked 'Push'", accuracy: 0.1, speed: 0.08, difficulty: 0.3 },
  { title: "Baller", subTitle: "on a budget", accuracy: 0.1, speed: 0.08, difficulty: 0.3 },
  { title: "Rockstar", subTitle: "air guitar edition", accuracy: 0.1, speed: 0.08, difficulty: 0.3 },
  { title: "Fearless", subTitle: "unless it’s spiders", accuracy: 0.1, speed: 0.08, difficulty: 0.3 },
  { title: "Adorable", subTitle: "like a gremlin", accuracy: 0.1, speed: 0.08, difficulty: 0.3 },
  { title: "Killer Move", subTitle: "still can’t dance though", accuracy: 0.2, speed: 0.16, difficulty: 0.4 },
  { title: "Godlike", subTitle: "but still can’t parallel park", accuracy: 0.2, speed: 0.16, difficulty: 0.4 },
  { title: "Nailed It", subTitle: "...like a sleepy carpenter", accuracy: 0.3, speed: 0.24, difficulty: 0.5 },
  { title: "Glorious", subTitle: "like glitter on everything", accuracy: 0.3, speed: 0.24, difficulty: 0.5 },
  { title: "Certified Genius", subTitle: "Yes, we checked the paperwork.", accuracy: 0.8, speed: 0.64, difficulty: 1 },
  { title: "Unstoppable", subTitle: "like a car without brakes", accuracy: 0.8, speed: 0.64, difficulty: 1 },
  { title: "Champ Champ", subTitle: "One trophy wasn’t enough.", accuracy: 0.9, speed: 0.72, difficulty: 1 },



  { title: 'Logic Leak', subTitle: 'Thoughts escaped faster than your streak score.', accuracy: -1, speed: -0.8, difficulty: -0.8 },
  { title: 'Equation Oops', subTitle: 'Wrong side, wrong time, wrong math.', accuracy: -1, speed: -0.8, difficulty: -0.8 },
  { title: 'Puzzle Panic', subTitle: 'Even the hints asked for hazard pay.', accuracy: -1, speed: -0.8, difficulty: -0.8 },
  { title: 'Fraction Fiasco', subTitle: 'Half right, half tragic.', accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: 'Number Nap', subTitle: 'You dreamed of accuracy, briefly.', accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: 'Graphical Error', subTitle: 'Your trendline went straight to regret.', accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: 'Puzzle Fumble', subTitle: 'You tripped over easy mode.', accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: 'Logic Lapse', subTitle: 'Brain went on vacation mid-problem.', accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: 'Math Mulligan', subTitle: 'You swung. The math ducked.', accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: 'Number Fog', subTitle: 'Visibility: zero. Accuracy: also zero.', accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: 'Sum Slip', subTitle: 'Missed the plus sign like it owed you money.', accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: 'Hint Hypocrite', subTitle: 'Begged for help, ignored it instantly.', accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: 'Logic Lag', subTitle: 'Your thoughts load slower than dial-up.', accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: 'Equation Shrug', subTitle: '"Math"? It\'s apparently more about the "vibes" for you.', accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: 'Clever Adjacent', subTitle: 'You almost brushed against smart.', accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: 'Angle Amnesia', subTitle: 'Every corner became confusion.', accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: 'Puzzle Plodder', subTitle: 'You took the scenic route to wrong.', accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: 'Fact Fumbler', subTitle: 'You misquoted the tutorial again.', accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: 'Logic Loiterer', subTitle: 'Lurking near the solution, uninvited.', accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: 'Count Confusion', subTitle: 'Ran out of fingers *and* guesses.', accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: 'Sum Stumbler', subTitle: 'Tripped over the equals sign again.', accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: 'Fraction Fidget', subTitle: 'Reduced yourself, not the fraction.', accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: 'Math Mischief', subTitle: 'Chaos is technically a method.', accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: 'Logic Babysitter', subTitle: 'Watched your reasoning fall off the couch.', accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: 'Digit Daydreamer', subTitle: 'Counting sheep instead of sums.', accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: 'Puzzle Rambler', subTitle: 'Talked through every wrong assertion proudly.', accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: 'Hypothesis Hobo', subTitle: 'Traveling light, no proof in sight.', accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: 'Sequence Snoozer', subTitle: 'The puzzle solved itself out of pity.', accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: 'Riddle Rambler', subTitle: 'You narrated failure beautifully.', accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: 'Clue Clinger', subTitle: 'Still holding the wrong one, champion.', accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: 'Math Mood Swing', subTitle: 'One step genius, one step chaos.', accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: 'Estimate Enthusiast', subTitle: 'Close enough… in an alternate reality.', accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: 'Digit Diplomat', subTitle: 'Brokered peace between two wrongs.', accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: 'Logic Looper', subTitle: 'Orbiting the answer without landing.', accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: 'Clue Juggler', subTitle: 'Dropped them all but smiled anyway.', accuracy: -0.1, speed: -0.08, difficulty: 0.1 },
  { title: 'Number Nudger', subTitle: 'Almost right counts for something.', accuracy: -0.1, speed: -0.08, difficulty: 0.1 },
  { title: 'Puzzle Shuffler', subTitle: 'Explored every option, none worked, tried anyway.', accuracy: -0.1, speed: -0.08, difficulty: 0.1 },
  { title: 'Mid Math', subTitle: 'Consistent mediocrity is still consistent.', accuracy: 0, speed: 0, difficulty: 0.2 },
  { title: 'Sum Slinger', subTitle: 'Accuracy optional, confidence mandatory.', accuracy: 0, speed: 0, difficulty: 0.2 },
  { title: 'Sum Strategist', subTitle: 'Brilliant plan, terrible follow-through.', accuracy: 0.1, speed: 0.08, difficulty: 0.3 },
  { title: 'Equation Acrobat', subTitle: 'Graceful stumble into correctness.', accuracy: 0.2, speed: 0.16, difficulty: 0.4 },
  { title: 'Puzzle Pilot', subTitle: 'Turbulent but landed somewhere.', accuracy: 0.2, speed: 0.16, difficulty: 0.4 },
  { title: 'Number Night Owl', subTitle: 'Smart after everyone stops watching.', accuracy: 0.2, speed: 0.16, difficulty: 0.4 },
  { title: 'Puzzle Polisher', subTitle: 'Shiny, but still wrong underneath.', accuracy: 0.3, speed: 0.24, difficulty: 0.5 },
  { title: 'Sum Surgeon', subTitle: 'Surgical precision, butter-knife results.', accuracy: 0.3, speed: 0.24, difficulty: 0.5 },
  { title: 'Grid Gladiator', subTitle: 'Won by sheer stubbornness.', accuracy: 0.3, speed: 0.24, difficulty: 0.5 },
  { title: 'Brainstorm Captain', subTitle: 'Steered through chaos, mostly upright.', accuracy: 0.3, speed: 0.24, difficulty: 0.5 },
  { title: 'Pattern Pathfinder', subTitle: 'Found the route, detoured anyway.', accuracy: 0.3, speed: 0.24, difficulty: 0.5 },
  { title: 'Logic Librarian', subTitle: 'Filed ideas under “close enough.”', accuracy: 0.4, speed: 0.32, difficulty: 0.6 },
  { title: 'Math Mechanic', subTitle: 'Runs fine if nobody looks closely.', accuracy: 0.4, speed: 0.32, difficulty: 0.6 },
  { title: 'Logic Captain', subTitle: 'Navigated perfectly into a minor reef.', accuracy: 0.5, speed: 0.4, difficulty: 0.7 },
  { title: 'Math Maverick', subTitle: 'Rules ignored, still worked somehow.', accuracy: 0.5, speed: 0.4, difficulty: 0.7 },
  { title: 'Sum Commander', subTitle: 'Bossed numbers until they gave up.', accuracy: 0.5, speed: 0.4, difficulty: 0.7 },
  { title: 'Brainwave Baron', subTitle: 'Charged rent for your own idea.', accuracy: 0.5, speed: 0.4, difficulty: 0.7 },
  { title: 'Equation Enforcer', subTitle: 'Made math behave with intimidation.', accuracy: 0.5, speed: 0.4, difficulty: 0.7 },
  { title: 'Math Maestro', subTitle: 'Conducted chaos in 4/4 time.', accuracy: 0.6, speed: 0.48, difficulty: 0.8 },
  { title: 'Grid Genius', subTitle: 'Too smug to double-check, still right.', accuracy: 0.6, speed: 0.48, difficulty: 0.8 },
  { title: 'Sum Supreme', subTitle: 'Stacked perfection, slightly crooked.', accuracy: 0.6, speed: 0.48, difficulty: 0.8 },
  { title: 'Logic Luminary', subTitle: 'Your glow gives everyone eye strain.', accuracy: 0.7, speed: 0.56, difficulty: 0.9 },
  { title: 'Equation Emperor', subTitle: 'Declared the answer by decree.', accuracy: 0.7, speed: 0.56, difficulty: 0.9 },
  { title: 'Puzzle Phenom', subTitle: 'Solved it fast, bragged faster.', accuracy: 0.8, speed: 0.64, difficulty: 1 },
  { title: 'Logic Royalty', subTitle: 'Crowned by sarcasm, worshipped by math.', accuracy: 0.9, speed: 0.72, difficulty: 1 },
  { title: 'Math Myth', subTitle: 'Half genius, half rumor.', accuracy: 0.9, speed: 0.72, difficulty: 1 },
  { title: 'Puzzle Paragon', subTitle: 'Too flawless to be likable.', accuracy: 0.9, speed: 0.72, difficulty: 1 },
  { title: 'Logic Demigod', subTitle: 'You bend logic just to stay amused.', accuracy: 1, speed: 0.8, difficulty: 1 },
  { title: 'Math Overlord', subTitle: 'The numbers whisper your name, trembling.', accuracy: 1, speed: 0.8, difficulty: 1 },
  { title: 'Math Mic Drop', subTitle: 'Dropped the proof, kept the applause.', accuracy: 1, speed: 0.8, difficulty: 1 },


  { title: 'Puzzle Panic', subTitle: 'Even the hints hid under the desk when you clicked.', accuracy: -1, speed: -0.8, difficulty: -0.8 },
  { title: 'Zero Hero', subTitle: 'You fought the numbers and zero clearly won.', accuracy: -1, speed: -0.8, difficulty: -0.8 },
  { title: 'Sum Disaster', subTitle: 'You brought subtraction to an addition fight.', accuracy: -1, speed: -0.8, difficulty: -0.8 },
  { title: 'Arithmetic Awkward', subTitle: 'You hugged the wrong move like it was family.', accuracy: -1, speed: -0.8, difficulty: -0.8 },
  { title: 'Almost Counted', subTitle: 'Four out of five mistakes recommend a redo.', accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: 'Algebra Oopsie', subTitle: 'Your X filed for a restraining order.', accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: 'Puzzle Fumble', subTitle: 'You tripped over the tutorial.', accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: 'Mist Calculation', subTitle: 'You turned basic arithmetic into abstract art.', accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: 'Number Nap', subTitle: 'Your brain took a break mid-subtraction.', accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: 'Carry Catastrophe', subTitle: 'You misplaced the one faster than your car keys.', accuracy: -0.9, speed: -0.72, difficulty: -0.7 },
  { title: 'Subtraction Sigh', subTitle: 'You borrowed ten and never gave it back.', accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: 'Equation Detour', subTitle: 'You took a scenic route through Wrong Answer Valley.', accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: 'Logic Lapse', subTitle: 'The clues waited while you rebooted your only thought.', accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: 'Number Fog', subTitle: 'Your vision of pi ends at three.', accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: 'Brain Buffering', subTitle: 'Your thoughts spin a loading wheel made of wrong answers.', accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: 'Hint Hypocrite', subTitle: 'You begged for clues and ignored every one.', accuracy: -0.8, speed: -0.64, difficulty: -0.6 },
  { title: 'Integer Itch', subTitle: 'You shuffled digits like a magician with no deck.', accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: 'Logic Lag', subTitle: 'Your reasoning arrives on dial-up.', accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: 'Guess Goblin', subTitle: 'You clicked random numbers and called it strategy.', accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: 'Number Nibble', subTitle: 'You took tiny bites out of the right answer and spit them out.', accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: 'Puzzle Pout', subTitle: 'You glared at the grid until it apologized.', accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: 'Equation Shrug', subTitle: 'You balanced the sides with pure indifference.', accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: 'Clever Adjacent', subTitle: 'You parked your brain next to the solution but never visited.', accuracy: -0.7, speed: -0.56, difficulty: -0.5 },
  { title: 'Tangent Tourist', subTitle: 'You treat every hint like a scenic overlook.', accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: 'Logic Loiterer', subTitle: 'You hang around the solution without making eye contact.', accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: 'Puzzle Plodder', subTitle: 'You set a personal best for undo clicks.', accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: 'Addition Overtime', subTitle: 'You took extra minutes to add two digits.', accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: 'Proofless', subTitle: 'You brought arguments, forgot the proof, and lost.', accuracy: -0.6, speed: -0.48, difficulty: -0.4 },
  { title: 'Count Confusion', subTitle: 'You counted on your fingers but ran out of fingers.', accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: 'Puzzle Plothole', subTitle: 'Your reasoning has more holes than a sieve chart.', accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: 'Equation Tourist', subTitle: 'You took selfies with every wrong step.', accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: 'Math Mischief', subTitle: 'You added drama, not numbers.', accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: 'Sum Stumbler', subTitle: 'You tripped over the equals sign.', accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: 'Abacus Amateur', subTitle: 'You poke the beads just to hear them sigh.', accuracy: -0.5, speed: -0.4, difficulty: -0.3 },
  { title: 'Equation Explorer', subTitle: 'You mapped every detour in Wrong Answer Canyon.', accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: 'Number Negotiator', subTitle: 'You tried bargaining with the sum like it was a yard sale.', accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: 'Logic Babysitter', subTitle: 'You keep your best ideas in time-out.', accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: 'Math Mood', subTitle: 'You only add when the vibes are right.', accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: 'Hypothesis Hobo', subTitle: 'You travel light and leave the proof behind.', accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: 'Digit Daydreamer', subTitle: 'You drift off mid-count like it is bedtime math.', accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: 'Puzzle Rambler', subTitle: 'You narrate every wrong guess like a podcast.', accuracy: -0.4, speed: -0.32, difficulty: -0.2 },
  { title: 'Sum Tourist', subTitle: 'You visited the right answer, bought a souvenir, then made the wrong move.', accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: 'Math Mood Swing', subTitle: 'You alternate between genius and "whoops" every other step.', accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: 'Logic Left Turn', subTitle: 'You signal right but proof left.', accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: 'Sequence Snoozer', subTitle: 'You nod off right before the pattern reveals itself.', accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: 'Riddle Rambler', subTitle: 'You turn every puzzle into a three-act monologue.', accuracy: -0.3, speed: -0.24, difficulty: -0.1 },
  { title: 'Brain Boot', subTitle: 'You reboot mid-puzzle like a vintage laptop.', accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: 'Math Middler', subTitle: 'You aim for mediocrity and nail it within decimals.', accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: 'Logic Looper', subTitle: 'You circle the answer like a shark with stage fright.', accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: 'Estimate Enthusiast', subTitle: 'You round everything until it sort of works.', accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: 'Calculator Consultant', subTitle: 'You ask it for advice then do the opposite.', accuracy: -0.2, speed: -0.16, difficulty: 0 },
  { title: 'Logic Jogger', subTitle: 'You warm up by missing the obvious clue.', accuracy: -0.1, speed: -0.08, difficulty: 0.1 },
  { title: 'Sum Stroller', subTitle: 'You take the scenic loop before tapping the right digit.', accuracy: -0.1, speed: -0.08, difficulty: 0.1 },
  { title: 'Digit Day Saver', subTitle: 'You rescue the puzzle fifteen minutes after it screamed.', accuracy: -0.1, speed: -0.08, difficulty: 0.1 },
  { title: 'Puzzle Shuffler', subTitle: 'You keep shuffling strategies like a deck of identical cards.', accuracy: -0.1, speed: -0.08, difficulty: 0.1 },
  { title: 'Mid Math', subTitle: 'You hit the median and called it destiny.', accuracy: 0, speed: 0, difficulty: 0.2 },
  { title: 'Digit Dealer', subTitle: 'You trade wrong digits for slightly better ones in bulk.', accuracy: 0, speed: 0, difficulty: 0.2 },
  { title: 'Sum Slinger', subTitle: 'You toss numbers at the board until one sticks.', accuracy: 0, speed: 0, difficulty: 0.2 },
  { title: 'Brainstorm Breeze', subTitle: 'Your ideas drift through and occasionally rain answers.', accuracy: 0, speed: 0, difficulty: 0.2 },
  { title: 'Puzzle Pacer', subTitle: 'You take steady laps around the finish line.', accuracy: 0.1, speed: 0.08, difficulty: 0.3 },
  { title: 'Equation Wrangler', subTitle: 'You rope in the numbers, then let one escape for drama.', accuracy: 0.1, speed: 0.08, difficulty: 0.3 },
  { title: 'Sum Strategist', subTitle: 'You planned five moves ahead and forgot step two.', accuracy: 0.1, speed: 0.08, difficulty: 0.3 },
  { title: 'Proof Patrol', subTitle: 'You check every step and still trip on the last one.', accuracy: 0.1, speed: 0.08, difficulty: 0.3 },
  { title: 'Pattern Prospector', subTitle: 'You find gold nuggets of logic then misplace them.', accuracy: 0.1, speed: 0.08, difficulty: 0.3 },
  { title: 'Sum Shepherd', subTitle: 'You herd stray digits back into formation, eventually.', accuracy: 0.2, speed: 0.16, difficulty: 0.4 },
  { title: 'Equation Acrobat', subTitle: 'You flip through operations with only "minor" face-plants.', accuracy: 0.2, speed: 0.16, difficulty: 0.4 },
  // { title: 'Number Night Owl', subTitle: 'You solve best when every sensible person is asleep.', mistakes: 0.2, timeSpent: 0.16, difficulty: 0.4 },
  { title: 'Proof Partner', subTitle: 'You hold the proof\'s hand and still trip.', accuracy: 0.2, speed: 0.16, difficulty: 0.4 },
  { title: 'Number Ninja', subTitle: 'You sneak past mistakes with barely a whisper.', accuracy: 0.9, speed: 0.72, difficulty: 1 },
  { title: 'Sum Surgeon', subTitle: 'You operate on problems with a slightly shaky scalpel.', accuracy: 0.3, speed: 0.24, difficulty: 0.5 },
  { title: 'Pattern Pathfinder', subTitle: 'You find the trail and still take a snack break mid-solve.', accuracy: 0.3, speed: 0.24, difficulty: 0.5 },
  { title: 'Math Mechanic', subTitle: 'You pop open the hood and pretend the noises are "features."', accuracy: 0.4, speed: 0.32, difficulty: 0.6 },
  { title: 'Puzzle Pathfinder', subTitle: 'You blaze trails through logic like a mildly lost scout.', accuracy: 0.4, speed: 0.32, difficulty: 0.6 },
  { title: 'Equation Engineer', subTitle: 'You bolt the pieces together until they mostly align.', accuracy: 0.4, speed: 0.32, difficulty: 0.6 },
  { title: 'Sumpreme Leader', subTitle: 'Your totals hold elections just to re-elect you.', accuracy: 1, speed: 0.8, difficulty: 1 },
  { title: 'Math Overlord', subTitle: 'The numbers unionized purely to slow you down.', accuracy: 1, speed: 0.8, difficulty: 1 },
  { title: 'Equation Elite', subTitle: 'You square up with problems and remind them who is boss.', accuracy: 0.8, speed: 0.64, difficulty: 1 },
  { title: 'Grid Governor', subTitle: 'You appoint numbers to positions they did not apply for.', accuracy: 0.8, speed: 0.64, difficulty: 1 },
  { title: 'Sum Superstar', subTitle: 'You autograph your totals to keep yourself grounded.', accuracy: 0.7, speed: 0.56, difficulty: 0.9 },
  { title: 'Grid Whisperer', subTitle: 'You talk the boxes into cooperating with mild sarcasm.', accuracy: 0.4, speed: 0.32, difficulty: 0.6 },
  { title: 'Math Maverick', subTitle: 'You ignore instructions and still stick the landing.', accuracy: 0.5, speed: 0.4, difficulty: 0.7 },
  { title: 'Equation Enforcer', subTitle: 'You smack both sides until they behave.', accuracy: 0.5, speed: 0.4, difficulty: 0.7 },
  { title: 'Sum Commander', subTitle: 'You bark orders at numbers, they mostly obey.', accuracy: 0.5, speed: 0.4, difficulty: 0.7 },
  
]
